workspace(name = "tbd")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "8e968b5fcea1d2d64071872b12737bbb5514524ee5f0a4f54f5920266c261acb",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.28.0/rules_go-v0.28.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.28.0/rules_go-v0.28.0.zip",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.16.5")




load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_gazelle",
    sha256 = "62ca106be173579c0a167deb23358fdfe71ffa1e4cfdddf5582af26520f1c66f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.23.0/bazel-gazelle-v0.23.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.23.0/bazel-gazelle-v0.23.0.tar.gz",
    ],
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()





load("//exporter:deps.bzl", "go_dependencies")
# gazelle:repository_macro exporter/deps.bzl%go_dependencies
go_dependencies()



http_archive(
    name = "com_google_protobuf",
    sha256 = "7d663c8dc81d282dc92e884b38e9c179671e31ccacce311154420e65f7d142c6",
    strip_prefix = "protobuf-3.13.0.1",
    urls = [
        "https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/v3.13.0.1.tar.gz",
        "https://github.com/protocolbuffers/protobuf/archive/v3.13.0.1.tar.gz",
    ],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "59d5b42ac315e7eadffa944e86e90c2990110a1c8075f1cd145f487e999d22b3",
    strip_prefix = "rules_docker-0.17.0",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.17.0/rules_docker-v0.17.0.tar.gz"],
)
load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load(
    "@io_bazel_rules_docker//go:image.bzl",
    _go_image_repos = "repositories",
)

_go_image_repos()

load(
    "@io_bazel_rules_docker//cc:image.bzl",
    _cc_image_repos = "repositories",
)

_cc_image_repos()

http_archive(
    name = "com_github_esnet_iperf",
    build_file = "iperf3-BUILD.bazel",
    sha256 = "c6d8076b800f2b51f92dc941b0a9b77fbf2a867f623b5cb3cbf4754dabc40899",
    strip_prefix = "iperf-3.9",
    urls = [
        "https://github.com/esnet/iperf/archive/3.9.tar.gz",
    ],
)

load("@io_bazel_rules_docker//container:container.bzl", "container_pull")

container_pull(
    name = "debian_base",
    digest = "sha256:819f12d5482276ee5ae8d8bb92853ef4ea82c762292de383d1e59d1804a7944f",
    registry = "index.docker.io",
    repository = "library/debian",
)

http_archive(
    name = "com_github_openvpn_openvpn",
    build_file = "openvpn-BUILD.bazel",
    sha256 = "d9fbeede4b650bfd9bac12384fbae3f90c26c07248d3031df171056c17a7f3a3",
    strip_prefix = "openvpn-2.5.0",
    urls = [
        "https://github.com/OpenVPN/openvpn/archive/v2.5.0.tar.gz",
    ],
)

http_archive(
    name = "openssl",
    build_file = "openssl-BUILD.bazel",
    sha256 = "23011a5cc78e53d0dc98dfa608c51e72bcd350aa57df74c5d5574ba4ffb62e74",
    strip_prefix = "openssl-OpenSSL_1_1_1d",
    urls = [
        "https://github.com/openssl/openssl/archive/OpenSSL_1_1_1d.tar.gz",
        "https://www.openssl.org/source/openssl-1.1.1d.tar.gz",
    ],
)

http_archive(
    name = "rules_foreign_cc",
    sha256 = "e14a159c452a68a97a7c59fa458033cc91edb8224516295b047a95555140af5f",
    strip_prefix = "rules_foreign_cc-0.4.0",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.4.0.tar.gz",
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

# This sets up some common toolchains for building targets. For more details, please see
# https://bazelbuild.github.io/rules_foreign_cc/0.4.0/flatten.html#rules_foreign_cc_dependencies
rules_foreign_cc_dependencies()

http_archive(
    name = "com_github_armmbed_mbedtls",
    build_file = "mbedtls-BUILD.bazel",
    sha256 = "d436ae4892bd80329ca18a3960052fbb42d3f1f46c7519711d6763621ca6cfa0",
    strip_prefix = "mbedtls-2.24.0",
    urls = [
        "https://github.com/ARMmbed/mbedtls/archive/v2.24.0.tar.gz",
    ],
)

http_archive(
    name = "org_kernel_iproute2",
    build_file = "iproute2-BUILD.bazel",
    patch_args = ["-p1"],
    patches = ["iproute2.patch"],
    sha256 = "1afde56d416f136b1236ac2f8276e4edbe114ca3c2ab12f11af11b84cf0992e4",
    strip_prefix = "iproute2-5.9.0",
    urls = [
        "https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/snapshot/iproute2-5.9.0.tar.gz",
        "https://github.com/shemminger/iproute2/archive/v5.9.0.tar.gz",
    ],
)

http_archive(
    name = "com_github_openvpn_easyrsa",
    build_file = "easyrsa-BUILD.bazel",
    sha256 = "1179453c18bc16316973545d4593c3f61a16bcddff7e1b749e1853bad7535593",
    strip_prefix = "easy-rsa-3.0.8",
    urls = [
        "https://github.com/OpenVPN/easy-rsa/archive/v3.0.8.zip",
    ],
)
